package com.example.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.demo.util.DynamoDBLocalDateTimeConverter;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.ToString;

import java.time.LocalDateTime;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@DynamoDBTable(tableName = User.TABLE_NAME)
@ToString(exclude = "password")
public class User {

    public static final String TABLE_NAME = "user";

    public static final String EMAIL_INDEX = "email-index";

    // attribute name
    public static final String ID_NAME = "id";
    public static final String EMAIL_NAME = "email";

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBLocalDateTimeConverter.class)
    private LocalDateTime created;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBLocalDateTimeConverter.class)
    private LocalDateTime lastModified;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = EMAIL_INDEX)
    private String email;

    private String password;
}
